[package]
name = "dots"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
